<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DnsClient" Version="1.8.0" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageReference Include="SauceControl.Blake2Fast" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ExplorationNativeTurnCapture" />
    <InternalsVisibleTo Include="ExplorationSessionValidation" />
  </ItemGroup>
</Project>
