using System.Globalization;

namespace SupercellProxy.Networking.Assets.Tables;

/// <summary>
/// Represents <c language="csharp">DataTableRegistry</c>.
/// </summary>
public static class DataTableRegistry
{
    private static readonly IReadOnlyDictionary<int, string> NativeDataTableFiles = new Dictionary<
        int,
        string
    >
    {
        [key: 1] = GameAssetFiles.Languages,
        [key: 2] = GameAssetFiles.Cars,
        [key: 3] = GameAssetFiles.Decorations,
        [key: 4] = GameAssetFiles.Fields,
        [key: 5] = GameAssetFiles.Forests,
        [key: 6] = GameAssetFiles.ProcessingBuildings,
        [key: 7] = GameAssetFiles.Sounds,
        [key: 8] = GameAssetFiles.Wonders,
        [key: 9] = GameAssetFiles.Tiles,
        [key: 10] = GameAssetFiles.Houses,
        [key: 11] = GameAssetFiles.AnimalHabitats,
        [key: 12] = GameAssetFiles.AnimalHabitatPieces,
        [key: 13] = GameAssetFiles.Animals,
        [key: 14] = GameAssetFiles.Warehouses,
        [key: 15] = GameAssetFiles.AnimalGoods,
        [key: 16] = GameAssetFiles.AnimalFeed,
        [key: 17] = GameAssetFiles.Boosters,
        [key: 18] = GameAssetFiles.Silos,
        [key: 19] = GameAssetFiles.Money,
        [key: 21] = GameAssetFiles.ConstructionBuildings,
        [key: 22] = GameAssetFiles.Tools,
        [key: 23] = GameAssetFiles.DairyGoods,
        [key: 24] = GameAssetFiles.BakeryGoods,
        [key: 25] = GameAssetFiles.CakeOvenGoods,
        [key: 26] = GameAssetFiles.PieOvenGoods,
        [key: 27] = GameAssetFiles.SugarMillGoods,
        [key: 28] = GameAssetFiles.LoomGoods,
        [key: 29] = GameAssetFiles.PopcornPotGoods,
        [key: 30] = GameAssetFiles.BarbecueGrillGoods,
        [key: 31] = GameAssetFiles.ExperienceLevels,
        [key: 32] = GameAssetFiles.OrderTables,
        [key: 33] = GameAssetFiles.PredefinedOrders,
        [key: 34] = GameAssetFiles.Orders,
        [key: 35] = GameAssetFiles.RoadsideShop,
        [key: 36] = GameAssetFiles.Tutorials,
        [key: 37] = GameAssetFiles.Events,
        [key: 38] = GameAssetFiles.CollectionTools,
        [key: 39] = GameAssetFiles.Scarecrows,
        [key: 40] = GameAssetFiles.Mailboxes,
        [key: 41] = GameAssetFiles.NewspaperStories,
        [key: 42] = GameAssetFiles.NewspaperLayout,
        [key: 43] = GameAssetFiles.CashPackages,
        [key: 44] = GameAssetFiles.DiamondPackages,
        [key: 45] = GameAssetFiles.AmbientAnimals,
        [key: 46] = GameAssetFiles.AmbientAnimalSpawners,
        [key: 47] = GameAssetFiles.Fonts,
        [key: 48] = GameAssetFiles.DecoFences,
        [key: 49] = GameAssetFiles.People,
        [key: 50] = GameAssetFiles.PeopleSpawners,
        [key: 51] = GameAssetFiles.TutorialPeopleOrders,
        [key: 52] = GameAssetFiles.Features,
        [key: 53] = GameAssetFiles.MysteryBoxes,
        [key: 54] = GameAssetFiles.MysteryBoxSpawners,
        [key: 55] = GameAssetFiles.AiRoadsideShop,
        [key: 56] = GameAssetFiles.Docks,
        [key: 57] = GameAssetFiles.Shacks,
        [key: 58] = GameAssetFiles.Boats,
        [key: 59] = GameAssetFiles.Achievements,
        [key: 60] = GameAssetFiles.JuicePressGoods,
        [key: 61] = GameAssetFiles.Fruits,
        [key: 62] = GameAssetFiles.FruitTrees,
        [key: 63] = GameAssetFiles.Mines,
        [key: 64] = GameAssetFiles.MineGoods,
        [key: 65] = GameAssetFiles.SmelterGoods,
        [key: 66] = GameAssetFiles.JamMakerGoods,
        [key: 67] = GameAssetFiles.Notifications,
        [key: 68] = GameAssetFiles.SpecialOrders,
        [key: 69] = GameAssetFiles.IceCreamMakerGoods,
        [key: 70] = GameAssetFiles.Boy,
        [key: 71] = GameAssetFiles.BoyBox,
        [key: 72] = GameAssetFiles.Faqs,
        [key: 73] = GameAssetFiles.MovieTickets,
        [key: 74] = GameAssetFiles.WheelCars,
        [key: 75] = GameAssetFiles.JewelerGoods,
        [key: 76] = GameAssetFiles.TrackingEvents,
        [key: 77] = GameAssetFiles.Vouchers,
        [key: 78] = GameAssetFiles.Pets,
        [key: 79] = GameAssetFiles.PetHabitats,
        [key: 80] = GameAssetFiles.Expansions,
        [key: 81] = GameAssetFiles.ExpansionFences,
        [key: 82] = GameAssetFiles.CafeGoods,
        [key: 83] = GameAssetFiles.Offers,
        [key: 84] = GameAssetFiles.CandyMachineGoods,
        [key: 85] = GameAssetFiles.ToolOffers,
        [key: 86] = GameAssetFiles.Rules,
        [key: 87] = GameAssetFiles.TargetedOffers,
        [key: 88] = GameAssetFiles.ScoreBoards,
        [key: 89] = GameAssetFiles.Balloons,
        [key: 90] = GameAssetFiles.Postman,
        [key: 91] = GameAssetFiles.GiftMailbox,
        [key: 92] = GameAssetFiles.Gifts,
        [key: 93] = GameAssetFiles.CatalogueLayout,
        [key: 94] = GameAssetFiles.CatalogueGifts,
        [key: 95] = GameAssetFiles.FishingBoat,
        [key: 96] = GameAssetFiles.FishingSpots,
        [key: 97] = GameAssetFiles.Fishes,
        [key: 98] = GameAssetFiles.Baits,
        [key: 99] = GameAssetFiles.FishingHut,
        [key: 100] = GameAssetFiles.BaitMaker,
        [key: 101] = GameAssetFiles.FishingGoods,
        [key: 102] = GameAssetFiles.TackleBox,
        [key: 103] = GameAssetFiles.EventBoard,
        [key: 104] = GameAssetFiles.CalendarEvents,
        [key: 105] = GameAssetFiles.Nets,
        [key: 106] = GameAssetFiles.NetMaker,
        [key: 107] = GameAssetFiles.LobsterPool,
        [key: 108] = GameAssetFiles.Lobsters,
        [key: 109] = GameAssetFiles.SoupKitchenGoods,
        [key: 110] = GameAssetFiles.Themes,
        [key: 111] = GameAssetFiles.EasterEggs,
        [key: 112] = GameAssetFiles.EasterEggSpawners,
        [key: 113] = GameAssetFiles.RewardLimits,
        [key: 114] = GameAssetFiles.CalendarEventRewards,
        [key: 115] = GameAssetFiles.NotificationsSettings,
        [key: 116] = GameAssetFiles.OpenGraphObjects,
        [key: 117] = GameAssetFiles.SushiBarGoods,
        [key: 118] = GameAssetFiles.SaladBarGoods,
        [key: 119] = GameAssetFiles.SauceMixerGoods,
        [key: 120] = GameAssetFiles.AdvanceSettings,
        [key: 121] = GameAssetFiles.SandwichBarGoods,
        [key: 122] = GameAssetFiles.OrderItemFilters,
        [key: 123] = GameAssetFiles.FacebookErrors,
        [key: 124] = GameAssetFiles.NeighborhoodBuildings,
        [key: 125] = GameAssetFiles.NeighborhoodBadges,
        [key: 126] = GameAssetFiles.FaqsLayout,
        [key: 127] = GameAssetFiles.AboutLayout,
        [key: 128] = GameAssetFiles.NeighborhoodJoinDelays,
        [key: 129] = GameAssetFiles.SmoothieMixerGoods,
        [key: 130] = GameAssetFiles.Drasine,
        [key: 131] = GameAssetFiles.Passenger,
        [key: 132] = GameAssetFiles.PassengerSpawners,
        [key: 133] = GameAssetFiles.TrainExpansions,
        [key: 134] = GameAssetFiles.ServiceBuildings,
        [key: 135] = GameAssetFiles.Train,
        [key: 136] = GameAssetFiles.ReputationLevels,
        [key: 137] = GameAssetFiles.TrainStations,
        [key: 138] = GameAssetFiles.TownHalls,
        [key: 139] = GameAssetFiles.PersonalTrain,
        [key: 140] = GameAssetFiles.TrainCrossings,
        [key: 141] = GameAssetFiles.PassengerBonus,
        [key: 142] = GameAssetFiles.NeighborhoodEventBoard,
        [key: 143] = GameAssetFiles.Names,
        [key: 144] = GameAssetFiles.TrainParts,
        [key: 145] = GameAssetFiles.SewingMachineGoods,
        [key: 146] = GameAssetFiles.GathererHabitats,
        [key: 147] = GameAssetFiles.GathererNests,
        [key: 148] = GameAssetFiles.GathererMines,
        [key: 149] = GameAssetFiles.Gatherers,
        [key: 150] = GameAssetFiles.GathererNestGoods,
        [key: 151] = GameAssetFiles.GathererMineResources,
        [key: 152] = GameAssetFiles.HoneyExtractorGoods,
        [key: 153] = GameAssetFiles.CandleMakerGoods,
        [key: 154] = GameAssetFiles.DuckSalon,
        [key: 155] = GameAssetFiles.Ducks,
        [key: 156] = GameAssetFiles.ExperienceLevelsThresholdRewards,
        [key: 157] = GameAssetFiles.TownRequestBoard,
        [key: 158] = GameAssetFiles.CircusTrains,
        [key: 159] = GameAssetFiles.CircusAnimals,
        [key: 160] = GameAssetFiles.CalendarEventsTown,
        [key: 161] = GameAssetFiles.CircusTrainParts,
        [key: 162] = GameAssetFiles.NeighborhoodTasks,
        [key: 163] = GameAssetFiles.Derby,
        [key: 164] = GameAssetFiles.DerbyRewards,
        [key: 165] = GameAssetFiles.DerbyThresholds,
        [key: 166] = GameAssetFiles.HatMakerGoods,
        [key: 167] = GameAssetFiles.HotdogStandGoods,
        [key: 168] = GameAssetFiles.PastaMakerGoods,
        [key: 169] = GameAssetFiles.PastaKitchenGoods,
        [key: 170] = GameAssetFiles.DecoDitches,
        [key: 171] = GameAssetFiles.DerbyLeagues,
        [key: 173] = GameAssetFiles.Regions,
        [key: 174] = GameAssetFiles.NeighborhoodDonationsArea,
        [key: 175] = GameAssetFiles.NeighborhoodRequestBoard,
        [key: 176] = GameAssetFiles.TacoKitchenGoods,
        [key: 177] = GameAssetFiles.TeaStandGoods,
        [key: 178] = GameAssetFiles.HelperHouse,
        [key: 179] = GameAssetFiles.Helpers,
        [key: 180] = GameAssetFiles.Lumberjack,
        [key: 181] = GameAssetFiles.HelperCharacters,
        [key: 182] = GameAssetFiles.HelperCollectionArea,
        [key: 183] = GameAssetFiles.StarterPackages,
        [key: 184] = GameAssetFiles.LimitedCollectionTools,
        [key: 185] = GameAssetFiles.PuzzlePieces,
        [key: 186] = GameAssetFiles.SpecialBoatRewards,
        [key: 187] = GameAssetFiles.SanctuaryAnimals,
        [key: 188] = GameAssetFiles.SanctuaryAnimalHabitats,
        [key: 189] = GameAssetFiles.SanctuaryBookstands,
        [key: 190] = GameAssetFiles.SanctuaryEvents,
        [key: 191] = GameAssetFiles.SanctuaryCollectionArea,
        [key: 192] = GameAssetFiles.PassengerAnimalBonus,
        [key: 193] = GameAssetFiles.Parachutes,
        [key: 195] = GameAssetFiles.CarOrderRewardSets,
        [key: 196] = GameAssetFiles.BoatOrderRewardSets,
        [key: 197] = GameAssetFiles.PassengerBonusSets,
        [key: 198] = GameAssetFiles.DerbyBingoRewards,
        [key: 199] = GameAssetFiles.Boombox,
        [key: 200] = GameAssetFiles.Deeplinks,
        [key: 201] = GameAssetFiles.NotificationsAndroidChannels,
        [key: 202] = GameAssetFiles.FlowerShopGoods,
        [key: 204] = GameAssetFiles.RenovatorStand,
        [key: 205] = GameAssetFiles.CustomizationTruck,
        [key: 206] = GameAssetFiles.CustomizationHouse,
        [key: 207] = GameAssetFiles.CustomizationRss,
        [key: 208] = GameAssetFiles.BuilderSpawners,
        [key: 209] = GameAssetFiles.Builders,
        [key: 210] = GameAssetFiles.CustomizationStyleguide,
        [key: 211] = GameAssetFiles.TownHallSettings,
        [key: 212] = GameAssetFiles.NeighborhoodTags,
        [key: 213] = GameAssetFiles.TextStyles,
        [key: 214] = GameAssetFiles.CalendarEventGiftBox,
        [key: 215] = GameAssetFiles.FarmBridge,
        [key: 216] = GameAssetFiles.MapGameNodes,
        [key: 217] = GameAssetFiles.MapGameTiles,
        [key: 218] = GameAssetFiles.MapGameTasks,
        [key: 219] = GameAssetFiles.MapGameCoins,
        [key: 220] = GameAssetFiles.MapGameQuests,
        [key: 221] = GameAssetFiles.MapGameDailyQuestsProgression,
        [key: 222] = GameAssetFiles.MapGameDecorations,
        [key: 223] = GameAssetFiles.MapGameStand,
        [key: 224] = GameAssetFiles.MapGameRewardSets,
        [key: 226] = GameAssetFiles.MapGameNotifications,
        [key: 227] = GameAssetFiles.MapGameSunpointsTasks,
        [key: 228] = GameAssetFiles.MapGameSunpointsTasksSpawningRules,
        [key: 229] = GameAssetFiles.MapGameSunpointsProgression,
        [key: 230] = GameAssetFiles.MapGameEmojis,
        [key: 231] = GameAssetFiles.MapGameShopRewards,
        [key: 232] = GameAssetFiles.MapGameBonusRoundConfiguration,
        [key: 233] = GameAssetFiles.MapGameBonusRoundRewardSets,
        [key: 234] = GameAssetFiles.MapGameBonusRoundRewardRules,
        [key: 235] = GameAssetFiles.Colors,
        [key: 236] = GameAssetFiles.ModularDecorations,
        [key: 237] = GameAssetFiles.ModularOptions,
        [key: 238] = GameAssetFiles.WokKitchenGoods,
        [key: 239] = GameAssetFiles.FonduePotGoods,
        [key: 240] = GameAssetFiles.DeepFryerGoods,
        [key: 241] = GameAssetFiles.BathKioskGoods,
        [key: 242] = GameAssetFiles.ModularDecorationPrices,
        [key: 243] = GameAssetFiles.PopStand,
        [key: 244] = GameAssetFiles.PopRewardSets,
        [key: 245] = GameAssetFiles.PopCollectionTools,
        [key: 246] = GameAssetFiles.Blacklists,
        [key: 247] = GameAssetFiles.SquirrelNestGoods,
        [key: 248] = GameAssetFiles.DonutMakerGoods,
        [key: 249] = GameAssetFiles.FarmPassTasks,
        [key: 250] = GameAssetFiles.FarmPassTasksWeeklySpawningRules,
        [key: 251] = GameAssetFiles.FarmPassNotifications,
        [key: 252] = GameAssetFiles.FarmPassPerks,
        [key: 253] = GameAssetFiles.AnimalAccessories,
        [key: 254] = GameAssetFiles.FarmPassRoadDecorations,
        [key: 255] = GameAssetFiles.FarmPassRoad,
        [key: 256] = GameAssetFiles.FarmPassBuilding,
        [key: 257] = GameAssetFiles.BabyPets,
        [key: 258] = GameAssetFiles.FarmPassTasksDailySpawningRules,
        [key: 259] = GameAssetFiles.ChickStand,
        [key: 260] = GameAssetFiles.MapGameMaps,
        [key: 261] = GameAssetFiles.PreservationStationGoods,
        [key: 262] = GameAssetFiles.PotteryStudioGoods,
        [key: 263] = GameAssetFiles.FudgeShopGoods,
        [key: 264] = GameAssetFiles.DecorationsWip,
        [key: 265] = GameAssetFiles.DecoFencesWip,
        [key: 266] = GameAssetFiles.DecoDitchesWip,
        [key: 267] = GameAssetFiles.YoghurtMakerGoods,
        [key: 268] = GameAssetFiles.CupcakeMakerGoods,
        [key: 270] = GameAssetFiles.SeasonalGoods,
        [key: 271] = GameAssetFiles.SeasonalCurrencies,
        [key: 272] = GameAssetFiles.SeasonalCatalogueGifts,
        [key: 273] = GameAssetFiles.SeasonalCatalogueLayout,
        [key: 275] = GameAssetFiles.LoadingScreenHints,
        [key: 276] = GameAssetFiles.BirthdayEventTasks,
        [key: 277] = GameAssetFiles.BirthdayEventTasksSpawningRules,
        [key: 282] = GameAssetFiles.CountyFairRewardSets,
        [key: 283] = GameAssetFiles.StreakTasks,
        [key: 284] = GameAssetFiles.CountyFairBonusRoundRewardSets,
        [key: 285] = GameAssetFiles.CountyFairDummyGoods,
        [key: 287] = GameAssetFiles.CountyFairBonusRoundConfiguration,
        [key: 288] = GameAssetFiles.CountyFairBonusRoundRewardRules,
        [key: 289] = GameAssetFiles.DecoStickerBookCollections,
        [key: 290] = GameAssetFiles.DecoStickerBookStand,
        [key: 291] = GameAssetFiles.DecorationEventCanvases,
        [key: 292] = GameAssetFiles.DecoEventChallenges,
        [key: 293] = GameAssetFiles.DecoEventBuilding,
        [key: 295] = GameAssetFiles.DecoEventBorders,
        [key: 296] = GameAssetFiles.PhotographerSpawners,
        [key: 297] = GameAssetFiles.Photographer,
        [key: 298] = GameAssetFiles.ProgressionModifiers,
        [key: 299] = GameAssetFiles.AiNames,
        [key: 300] = GameAssetFiles.TutorialGroups,
        [key: 301] = GameAssetFiles.PeopleSpawnersRewards,
        [key: 302] = GameAssetFiles.PeopleRewardSets,
        [key: 303] = GameAssetFiles.PeopleSpawnersOrderExcludes,
        [key: 304] = GameAssetFiles.CollectionToolsRemap,
        [key: 307] = GameAssetFiles.SiloPricing,
        [key: 308] = GameAssetFiles.BarnPricing,
        [key: 309] = GameAssetFiles.PredefinedBoatOrders,
        [key: 310] = GameAssetFiles.NewspaperBotCategories,
        [key: 311] = GameAssetFiles.CreatureDefinitions,
        [key: 312] = GameAssetFiles.CreatureMovementBehaviors,
        [key: 313] = GameAssetFiles.CreatureRewards,
        [key: 314] = GameAssetFiles.CreatureSpawnRules,
        [key: 315] = GameAssetFiles.MiniPasses,
        [key: 316] = GameAssetFiles.MiniPassTasks,
        [key: 319] = GameAssetFiles.FreshBeatBuckets,
        [key: 320] = GameAssetFiles.FreshBeatBucketGroups,
        [key: 321] = GameAssetFiles.NeighborhoodObjects,
        [key: 322] = GameAssetFiles.NeighborhoodObjectTasks,
        [key: 323] = GameAssetFiles.Emotes,
        [key: 325] = GameAssetFiles.NeighborhoodObjectPerks,
        [key: 326] = GameAssetFiles.WeightedRewardGroups,
        [key: 327] = GameAssetFiles.OrderTracks,
        [key: 328] = GameAssetFiles.FakeRewards,
        [key: 329] = GameAssetFiles.OrderTrackGroups,
        [key: 330] = GameAssetFiles.FeaturesUnlock,
        [key: 331] = GameAssetFiles.DecisionBoxes,
        [key: 332] = GameAssetFiles.TruckDifficulties,
        [key: 333] = GameAssetFiles.BoatDailyModifiers,
        [key: 335] = GameAssetFiles.PeopleFriendship,
        [key: 336] = GameAssetFiles.PeopleQuests,
        [key: 337] = GameAssetFiles.PeopleQuestArchetypes,
        [key: 338] = GameAssetFiles.OrderTrackConfigs,
        [key: 339] = GameAssetFiles.Workbench,
        [key: 340] = GameAssetFiles.WorkbenchBuildings,
        [key: 341] = GameAssetFiles.WorkbenchMaterials,
        [key: 342] = GameAssetFiles.BoatDifficulties,
        [key: 343] = GameAssetFiles.WorkbenchPerks,
        [key: 344] = GameAssetFiles.BoatOrderModifiers,
        [key: 345] = GameAssetFiles.ProcessingBuildingsWip,
        [key: 346] = GameAssetFiles.BirthdayEventBonusRound,
        [key: 347] = GameAssetFiles.BirthdayEventBonusRoundConfiguration,
        [key: 348] = GameAssetFiles.BirthdayEventBonusRoundRewardSets,
        [key: 349] = GameAssetFiles.BirthdayEventBonusRoundRewardRules,
        [key: 350] = GameAssetFiles.BoatDestinations,
        [key: 351] = GameAssetFiles.ScidPopups,
        [key: 352] = GameAssetFiles.Molluscs,
        [key: 353] = GameAssetFiles.MolluscGoods,
        [key: 354] = GameAssetFiles.MolluscBeds,
        [key: 355] = GameAssetFiles.PeopleQuestProductGroups,
        [key: 356] = GameAssetFiles.FarmPassDiamondSkip,
        [key: 357] = GameAssetFiles.Angus,
        [key: 358] = GameAssetFiles.FarmPassLoopRewards,
    };

    /// <summary>
    /// Creates a <c language="csharp">DataTableRegistry</c> from the supplied data.
    /// </summary>
    public static IReadOnlyDictionary<int, string> Create(IEnumerable<GameAsset> resources)
    {
        Dictionary<string, GameAsset> resourcesByFile = resources.ToDictionary(static resource => resource.Fingerprint.File, StringComparer.Ordinal);

        Dictionary<int, string> dataTableFiles = new(NativeDataTableFiles);

        if (!resourcesByFile.TryGetValue(GameAssetFiles.ProductionBuildingsGoods, out GameAsset? productionBuildingsGoodsResource))
            throw new InvalidOperationException($"GameAsset {GameAssetFiles.ProductionBuildingsGoods} was not downloaded.");

        if (!productionBuildingsGoodsResource.TryGetTable(out GameDataTable? productionBuildingsGoods))
            throw new InvalidOperationException($"Failed to parse {GameAssetFiles.ProductionBuildingsGoods}.");

        foreach (GameDataTableEntry entry in productionBuildingsGoods.Entries)
        {
            string csvName = ReadText(entry, field: "CsvName");
            int exportNumber = ReadNumber(entry, field: "ExportNum");

            if (dataTableFiles.TryGetValue(exportNumber, out string? existingFile) && !existingFile.Equals(csvName, StringComparison.Ordinal))
                throw new InvalidDataException(string.Create(CultureInfo.InvariantCulture, $"Data table {exportNumber} maps to both {existingFile} and {csvName}."));

            dataTableFiles[exportNumber] = csvName;
        }

        return dataTableFiles;
    }

    private static InvalidDataException InvalidEntry()
    {
        return new($"Invalid entry in {GameAssetFiles.ProductionBuildingsGoods}.");
    }

    private static int ReadNumber(GameDataTableEntry entry, string field)
    {
        return entry.BaseRow.TryGetValue(field, out LiteralValue cell) && cell.TryGetInt32(out int number)
            ? number
            : throw InvalidEntry();
    }

    private static string ReadText(GameDataTableEntry entry, string field)
    {
        return entry.BaseRow.TryGetValue(field, out LiteralValue cell) && cell.TryGetString(out string? text)
            ? text
            : throw InvalidEntry();
    }
}
