using System.Globalization;
using SupercellProxy.Playground.Data.Assets;
using SupercellProxy.Playground.Data.Tables;
using SupercellProxy.Playground.Logic;

namespace SupercellProxy.Playground.Home;

internal sealed record AnimalHabitatPieceState(
    GameObjectState GameObject,
    int AnimalHabitatGlobalId
)
{
    public static AnimalHabitatPieceState[] Resolve(
        GameObjectState[] gameObjects,
        DataTableResolver dataTableResolver,
        GameRandom constructorRandom
    )
    {
        if (
            !dataTableResolver.TryGetTableId(
                GameAssetFiles.AnimalHabitats,
                out var animalHabitatTableId
            )
        )
            throw new InvalidOperationException(
                $"{GameAssetFiles.AnimalHabitats} is not registered as a native data table."
            );

        if (
            !dataTableResolver.TryGetTableId(
                GameAssetFiles.AnimalHabitatPieces,
                out var animalHabitatPieceTableId
            )
        )
            throw new InvalidOperationException(
                $"{GameAssetFiles.AnimalHabitatPieces} is not registered as a native data table."
            );

        if (gameObjects.Any(gameObject => gameObject.Data.TableId == animalHabitatPieceTableId))
            throw new InvalidDataException(
                "Animal habitat pieces must be generated by their native habitat constructor."
            );

        var pieces = new List<AnimalHabitatPieceState>();

        foreach (
            var animalHabitat in gameObjects.Where(gameObject =>
                gameObject.Data.TableId == animalHabitatTableId
            )
        )
        {
            CreatePiecesForHabitat(
                pieces,
                animalHabitat,
                animalHabitatPieceTableId,
                GameAssetFiles.AnimalHabitatPieces,
                dataTableResolver
            );
        }

        return pieces.ToArray();
    }

    private static void CreatePiecesForHabitat(
        List<AnimalHabitatPieceState> pieces,
        GameObjectState animalHabitat,
        int animalHabitatPieceTableId,
        string animalHabitatPiecesFile,
        DataTableResolver dataTableResolver
    )
    {
        if (
            !dataTableResolver.TryResolveValueCount(
                animalHabitat.Data.GlobalId,
                "Piece",
                out var pieceCount
            )
            || !dataTableResolver.TryResolveInt(
                animalHabitat.Data.GlobalId,
                "TileWidth",
                out var habitatTileWidth
            )
            || !dataTableResolver.TryResolveInt(
                animalHabitat.Data.GlobalId,
                "TileHeight",
                out var habitatTileHeight
            )
        )
        {
            throw new InvalidDataException(
                string.Create(
                    CultureInfo.InvariantCulture,
                    $"Animal habitat {animalHabitat.Data.GlobalId} has incomplete piece data."
                )
            );
        }

        var firstPieceInstanceId = pieces.Count;
        for (var pieceIndex = 0; pieceIndex < pieceCount; pieceIndex++)
        {
            pieces.Add(
                CreatePiece(
                    animalHabitat,
                    animalHabitatPieceTableId,
                    animalHabitatPiecesFile,
                    dataTableResolver,
                    firstPieceInstanceId,
                    pieceCount,
                    pieceIndex,
                    habitatTileWidth,
                    habitatTileHeight
                )
            );
        }
    }

    private static AnimalHabitatPieceState CreatePiece(
        GameObjectState habitat,
        int pieceTableId,
        string piecesFile,
        DataTableResolver resolver,
        int firstInstanceId,
        int pieceCount,
        int pieceIndex,
        int habitatWidth,
        int habitatHeight
    )
    {
        if (
            !resolver.TryResolveString(
                habitat.Data.GlobalId,
                "Piece",
                pieceIndex,
                out var pieceName
            )
            || !resolver.TryResolve(piecesFile, pieceName, out var pieceData)
            || !resolver.TryResolveInt(
                habitat.Data.GlobalId,
                "PieceTileX",
                pieceIndex,
                out var tileX
            )
            || !resolver.TryResolveInt(
                habitat.Data.GlobalId,
                "PieceTileY",
                pieceIndex,
                out var tileY
            )
            || !resolver.TryResolveBoolean(
                habitat.Data.GlobalId,
                "PieceMirrored",
                pieceIndex,
                out var mirrored
            )
        )
            throw new InvalidDataException(
                string.Create(
                    CultureInfo.InvariantCulture,
                    $"Animal habitat {habitat.Data.GlobalId} has incomplete piece {pieceIndex} data."
                )
            );

        var dimensions = GameObjectDimensionsResolver.Resolve(pieceData, resolver);
        var snapshot = new GameObjectSnapshot
        {
            DataGlobalId = pieceData.GlobalId,
            AccurateX = GetPosition(tileX, habitatWidth),
            AccurateY = GetPosition(tileY, habitatHeight),
            Mirrored = mirrored,
        };
        var gameObject = new GameObjectState(
            pieceTableId * DataTableResolver.GlobalIdTableSize
                + firstInstanceId
                + pieceCount
                - pieceIndex
                - 1,
            snapshot,
            pieceData,
            dimensions.Width,
            dimensions.Height
        );
        gameObject.AttachTo(habitat);
        return new AnimalHabitatPieceState(gameObject, habitat.GlobalId);
    }

    private static int GetPosition(int tilePosition, int habitatTileSize)
    {
        return unchecked((tilePosition << 9) - (tilePosition == habitatTileSize ? 1 : 0));
    }
}
