name: Get Server Public Key

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct URL to any Supercell game IPA file or libg.so dump'
        default: 'temp.sh'
        required: true
        type: string

jobs:
  extract-server-public-key:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: 'latest'

      - name: Get Server Public Key
        run: dotnet run --project src/SupercellProxy.PublicKeyExtractor -- "${{ inputs.file_url }}" | tee -a "$GITHUB_STEP_SUMMARY"
