name: Get Server Public Key

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct URL to any Supercell game IPA file or libg.so dump'
        default: 'temp.sh'
        required: true
        type: string

jobs:
  extract-server-public-key:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        with:
          dotnet-version: '10'

      - name: Get Server Public Key
        run: dotnet run --project src/SupercellProxy.PublicKeyExtractor -- "${{ inputs.file_url }}" | tee -a "$GITHUB_STEP_SUMMARY"
