name: Get Server Public Key

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct URL to any Supercell game IPA file or libg.so dump'
        default: 'temp.sh'
        required: true
        type: string

jobs:
  extract-server-public-key:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
        with:
          dotnet-version: 'latest'

      - name: Get Server Public Key
        run: dotnet run --project src/SupercellProxy.PublicKeyExtractor -- "${{ inputs.file_url }}" | tee -a "$GITHUB_STEP_SUMMARY"
